#!/bin/bash

echo "Scaling the app to 3 replicas....."
kubectl scale deployment django-app --replicas=3
if [ $? -ne 0 ]; then
    echo "❌ Failed to scale deployment. Exiting."
    exit 1
fi

echo "✅ Listing all current pods..."
kubectl get pods

# Check if wrk is installed
if ! command -v wrk > /dev/null; then
    echo "📦 Installing wrk from source..."

    sudo apt-get update
    sudo apt-get install -y build-essential libssl-dev git

    git clone https://github.com/wg/wrk.git /tmp/wrk
    cd /tmp/wrk && make

    sudo cp wrk /usr/local/bin/
    cd -
    
    if ! command -v wrk > /dev/null; then
        echo "❌ Failed to install wrk. Exiting ..."
        exit 1
    fi
fi

echo "🌐 Getting service URL from Minikube..."
SERVICE_IP=$(minikube service django-service --url)

if [ -z "$SERVICE_IP" ]; then
    echo "❌ Failed to retrieve service IP. Exiting..."
    exit 1
fi

echo "🚀 Running load testing with wrk..."
wrk -t2 -c100 -d30s "$SERVICE_IP"

echo "📊 Checking Resource Usage..."
kubectl top pods
