#!/bin/bash
if ! command -v minikube &> /dev/null; then
    echo "Minikube not installed."
fi

echo "Starting minikube cluster..."
minikube start --driver=docker

echo "Checking Cluster Status...."
kubectl cluster-info

echo "Listing all pods in the cluster...."
kubectl get pods --all-namespaces