#!/bin/bash
if ! command -v minikube &> /dev/null; then
    echo "Minikube not found. Installing minikube ......."
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube
fi

echo "Starting Minikube Cluster....."
minikube start --driver=docker

echo "Checking Cluster Status....."
kubectl cluster-info

echo "Listing all pods in the cluster...."
kubectl get pods --all-namespaces