name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: messaging_app
          POSTGRES_USER: allan
          POSTGRES_PASSWORD: Allan20252025
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U allan"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DATABASE_URL: postgres://allan:Allan20252025@127.0.0.1:5432/messaging_app
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        env:
          DATABASE_URL: postgres://allan:Allan20252025@127.0.0.1:5432/messaging_app
        run: |
          pytest --verbose