# Generated by Django 5.2.1 on 2025-06-11 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_sender__3bd64e_idx',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', 'timestamp'], name='messaging_m_sender__0023f8_idx'),
        ),
    ]
